### PR TITLE
Fix opengl cmake for latest VTK

### PR DESCRIPTION
**Pull request by jspanchu**
This PR updates the CMake and `vtk.module` files.

- It correctly handles the definition of `VTK_USE_COCOA` macro. The previous approach is not the recommended way.
- Removes explicit dependency on `VTK::opengl`. The dependency on `VTK::RenderingOpenGL2` should've been sufficient.

### CODE REVIEW

**Comment by jspanchu** [comment]
@sankhesh, Actions are green! could you get someone with access to the device test out this PR?

**Comment by sankhesh** [comment]
@psavery has a device to test with.

**Comment by psavery** [comment]
This worked for me, although I'll note that my device is no longer supported by Looking Glass, and I have to use an older version of their service that they don't support anymore either.

However, since this PR is not intending to upgrade to their newer versions of the API, it looks good to me! Merge when ready.

**Comment by jspanchu** [comment]
Thanks for testing @psavery! Can someone with write access please merge this PR?

**Pull request merged**
